name: Generate Snake Game from Contributions

on:
  # Executa a ação sempre que há um novo push no repositório
  push:
    branches:
      - master  # ou main, dependendo do seu branch padrão
  # Executa a ação todos os dias, à meia-noite
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Puxa o repositório para a máquina virtual
      - uses: actions/checkout@v2

      # Executa a ação de gerar o gráfico da cobrinha
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Faz o upload da imagem gerada para o repositório
      - uses: actions/upload-artifact@v2
        with:
          name: snake-game
          path: dist