name: Generate Snake Game from Contributions

on:
  push:
    branches:
      - main  # ou 'master', dependendo do seu branch principal
  schedule:
    - cron: "0 0 * * *"  # Executa todos os dias à meia-noite

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Upload artifact
        uses: actions/upload-artifact@v3  # Atualizado para v3
        with:
          name: github-snake
          path: dist/github-snake.svg
